### ISSUE TITLE
Cannot respec character to the same name

### ISSUE THREAD

**Issue by AgainPsychoX** [ThyWoof/SolastaRespec#2]
Cannot respec character to the same name, because "there already exist character with that name". 

Workaround: Removing the character from list in the game menu helps.

_While there is workaround, it would be nice not to rely on it._

**Comment by ThyWoof** [comment]
Thanks. Game has a character pool service that I need to use for Respec. Most likely it's trying to validate the name against the pool. Seems to be an easy fix. Will look into it.

**Comment by ThyWoof** [comment]
Fixed a while ago...
