### ISSUE TITLE
Respecialize anywhere (feature request or question why not possible)

### ISSUE THREAD

**Issue by AgainPsychoX** [ThyWoof/SolastaRespec#3]
Why respecialization is required on global map rather than long rest or come button from inside the mod menu? It would be nicer to have it anywhere... Is is strict reason?

**Comment by ThyWoof** [comment]
It doesn't make much sense to do it from the Characters Menu... Simply create a new character. In game location is possible but still need to learn how to refresh the GuiCharacter there...
